<script setup lang="ts">
/**
 * Port of `src/app/(app)/opportunities/[id]/page.tsx`.
 *
 * `params` becomes `useRoute().params`; `notFound()` becomes a 404 thrown with
 * `createError`, which Nuxt renders through the error page.
 *
 * GAP: both the read and the status write went straight to Prisma and
 * MIGRATION.md §4 exposes no opportunities endpoint. They are wired to
 * `GET /api/opportunities/:id` and `PATCH /api/opportunities/:id`, the routes
 * such endpoints would occupy. The `Block` helper is inlined; `readEvidence`
 * and `defaultEmployees` are copied verbatim.
 */
import { formatRange, relativeTime } from "~/utils/format";
import { STAGE_LABELS, STAGE_TONES } from "~/components/dashboard/constants";
import { errorMessage } from "~/components/dashboard/api";
import type { LeadStage } from "~~/server/generated/prisma/client";

const STATUSES = ["OPEN", "ACCEPTED", "PARKED", "REJECTED"];

type OpportunityDetail = {
  id: string;
  title: string;
  problem: string;
  solution: string;
  benefit: string | null;
  status: string;
  confidence: number;
  createdAt: string;
  evidence: unknown;
  estimatedValueMin: number | null;
  estimatedValueMax: number | null;
  company: {
    id: string;
    name: string;
    industry: string | null;
    employeeCount: number | null;
  };
  lead: {
    id: string;
    stage: LeadStage;
    overallScore: number | null;
    fitScore: number | null;
  };
  roi: {
    employees: number;
    hoursPerWeek: number;
    hourlyCost: number;
    projectCost: number | null;
    prospectSupplied: boolean;
  } | null;
};

const route = useRoute();
const toast = useToast();
const id = computed(() => String(route.params.id));

const { data: opportunity, refresh } = await useFetch(
  () => `/api/opportunities/${id.value}`,
  {
    key: "opportunity-detail",
    transform: (res) => (res as unknown as { data: OpportunityDetail }).data,
  },
);

if (!opportunity.value) {
  throw createError({ statusCode: 404, statusMessage: "Page not found", fatal: true });
}

/** Evidence is stored as free-form JSON; render whatever list is in there. */
function readEvidence(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map((entry) =>
      typeof entry === "string" ? entry : JSON.stringify(entry),
    );
  }
  if (value && typeof value === "object") {
    return Object.values(value as Record<string, unknown>).flatMap((entry) =>
      typeof entry === "string" ? [entry] : [],
    );
  }
  return [];
}

/**
 * A starting point only, and a conservative one: a small share of headcount
 * rather than the whole company. The user is expected to replace it with what
 * the prospect actually says.
 */
function defaultEmployees(companySize: number | null) {
  if (!companySize) return 2;
  return Math.max(1, Math.min(10, Math.round(companySize * 0.05)));
}

const evidence = computed(() => readEvidence(opportunity.value?.evidence));

const roiInitial = computed(() => {
  const roi = opportunity.value?.roi;
  return {
    employees:
      roi?.employees ?? defaultEmployees(opportunity.value?.company.employeeCount ?? null),
    hoursPerWeek: roi?.hoursPerWeek ?? 5,
    hourlyCost: roi?.hourlyCost ?? 35,
    projectCost: roi?.projectCost ?? null,
    prospectSupplied: roi?.prospectSupplied ?? false,
    saved: Boolean(roi),
  };
});

const otherStatuses = computed(() =>
  STATUSES.filter((s) => s !== opportunity.value?.status),
);

/** `setOpportunityStatusAction`; `revalidatePath` becomes `refresh()`. */
async function setStatus(status: string) {
  try {
    await $fetch(`/api/opportunities/${id.value}`, { method: "PATCH", body: { status } });
    await refresh();
  } catch (e) {
    toast.add({
      severity: "error",
      summary: "Could not change the status",
      detail: errorMessage(e),
      life: 6000,
    });
  }
}
</script>

<template>
  <div v-if="opportunity">
    <UiPageHeader
      :title="opportunity.title"
      :description="`${opportunity.company.name}${opportunity.company.industry ? ` · ${opportunity.company.industry}` : ''}`"
    >
      <template #action>
        <div class="flex items-center gap-2">
          <UiBadge :tone="STAGE_TONES[opportunity.lead.stage]">
            {{ STAGE_LABELS[opportunity.lead.stage] }}
          </UiBadge>
          <NuxtLink :to="`/leads/${opportunity.lead.id}`">
            <UiButton size="sm">Open lead</UiButton>
          </NuxtLink>
        </div>
      </template>
    </UiPageHeader>

    <div class="space-y-4">
      <UiCard>
        <UiCardHeader
          title="The case"
          :description="`Confidence ${Math.round(opportunity.confidence * 100)}%. Generated by the opportunity agent — treat it as an argument to verify, not a finding.`"
        >
          <template #action>
            <form class="flex items-center gap-1" @submit.prevent>
              <UiButton
                v-for="status in otherStatuses"
                :key="status"
                type="button"
                size="sm"
                @click="setStatus(status)"
              >
                {{ status.toLowerCase() }}
              </UiButton>
            </form>
          </template>
        </UiCardHeader>
        <UiCardBody class="space-y-3">
          <div>
            <p class="text-xs font-medium text-muted">Problem</p>
            <p class="mt-1 text-sm whitespace-pre-line">{{ opportunity.problem }}</p>
          </div>
          <div>
            <p class="text-xs font-medium text-muted">Recommended solution</p>
            <p class="mt-1 text-sm whitespace-pre-line">{{ opportunity.solution }}</p>
          </div>
          <div v-if="opportunity.benefit">
            <p class="text-xs font-medium text-muted">Business benefit</p>
            <p class="mt-1 text-sm whitespace-pre-line">{{ opportunity.benefit }}</p>
          </div>
          <div
            class="flex flex-wrap gap-4 border-t border-border pt-3 text-xs text-muted"
          >
            <span>
              Estimated value
              {{
                formatRange(
                  opportunity.estimatedValueMin,
                  opportunity.estimatedValueMax,
                )
              }}
            </span>
            <span>Status {{ opportunity.status.toLowerCase() }}</span>
            <span>Created {{ relativeTime(opportunity.createdAt) }}</span>
          </div>
        </UiCardBody>
      </UiCard>

      <UiCard v-if="evidence.length > 0">
        <UiCardHeader
          title="Evidence"
          description="What this opportunity rests on. Anything not listed here is inference."
        />
        <UiCardBody>
          <ul class="space-y-1 text-sm">
            <li v-for="(item, index) in evidence" :key="index" class="text-muted">
              <a
                v-if="item.startsWith('http')"
                :href="item"
                target="_blank"
                rel="noreferrer noopener"
                class="text-accent hover:underline"
              >
                {{ item }}
              </a>
              <template v-else>{{ item }}</template>
            </li>
          </ul>
        </UiCardBody>
      </UiCard>

      <DashboardRoiCalculator :opportunity-id="opportunity.id" :initial="roiInitial" />
    </div>
  </div>
</template>
